# Generated by Django 5.0.1 on 2024-05-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beauty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='locality',
            name='state',
        ),
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='country',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.DeleteModel(
            name='AdministrativeArea',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
